### ISSUE TITLE
Warning from the characteristic 'On'

### ISSUE THREAD

**Issue by cbschuld** [shnhrrsn/homebridge-openzwave#17]
**THANK YOU** for working on this plugin.  I am seeing this in HomeBridge's log (_rpi3, running the homebridge image_).

Aeotec Gen5 stick.

```
[19/03/2021, 16:06:43] [homebridge-openzwave] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
```

In debug mode it it produces the following output:

```
Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1915:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at callback (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/platformDriver.ts:48:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by mikest** [comment]
I also see this error with a Nortek ZWave adapter.

**Comment by matellis** [comment]
Same for me on Gen5 Aeotec zwave stick
