### ISSUE TITLE
Loading issue after Node.js update

### ISSUE THREAD

**Issue by fxpa** [shnhrrsn/homebridge-openzwave#27]
Hello

I've update Node js for others plugins and resintall openzwave with this command because it was not working 

> sudo CXXFLAGS="--std=c++14" npm i -g homebridge-openzwave

After restart the plugin show an error

[08/05/2022, 08:00:49] ====================
[08/05/2022, 08:00:49] ERROR LOADING PLUGIN homebridge-openzwave:
[08/05/2022, 08:00:49] Error: Cannot find module 'homebridge'
Require stack:
- /usr/lib/node_modules/homebridge-openzwave/lib/Values/ValueCoordinator.js
- /usr/lib/node_modules/homebridge-openzwave/lib/Accessories/Drivers/Support/registerCharacteristic.js
- /usr/lib/node_modules/homebridge-openzwave/lib/Accessories/Drivers/batteryDriver.js
- /usr/lib/node_modules/homebridge-openzwave/lib/Accessories/Registries/StandardDriverRegistry.js
- /usr/lib/node_modules/homebridge-openzwave/lib/Accessories/AccessoryManager.js
- /usr/lib/node_modules/homebridge-openzwave/lib/Platform.js
- /usr/lib/node_modules/homebridge-openzwave/lib/registerPlatform.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openzwave/src/Values/ValueCoordinator.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/Support/registerCharacteristic.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/batteryDriver.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
[08/05/2022, 08:00:49] ====================

I don't know what to do next

**Comment by jbielick** [comment]
I think you want to install that module into `/var/lib/homebridge`, not `-g` (global) which is installing it to `/usr/lib/node_modules`.
