### ISSUE TITLE
Failed to make accessory

### ISSUE THREAD

**Issue by yurra2** [shnhrrsn/homebridge-openzwave#3]
I have two zway devices - smart switch and multisensor.
I was able to connect plugin to my openzway, but it creates just one Switch.
Seems like i am missing something in my config, but i am not sure.

 [2020-5-1 13:30:52] [Z-Wave Platform] Node Available: RaZberry Controller
[2020-5-1 13:30:56] [Z-Wave Platform] Failed to make accessory Error: homekitToZwave is required for readwrite values
    at new ValueCoordinator (/usr/lib/node_modules/homebridge-openzwave/src/Values/ValueCoordinator.ts:44:10)
    at registerCharacteristic (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/Support/registerCharacteristic.ts:27:2)
    at driver (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/batteryDriver.ts:36:2)
    at Accessory.configure (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Accessory.ts:72:4)
    at /usr/lib/node_modules/homebridge-openzwave/src/Accessories/AccessoryManager.ts:112:15
[2020-5-1 13:30:56] [Z-Wave Platform] Node Available: 4 - DSC24 Smart Switch (2nd Edition) (0x0018)
[2020-5-1 13:30:56] [Z-Wave Platform] Finished Scanning

**Comment by shnhrrsn** [comment]
Unfortunate battery powered devices don’t quite work yet.  There’s been progress made in master (and released as 1.1.0-beta.1), that fixes issues with handling sleep mode and assuming all devices are readwrite but it's definitely unstable.

Hoping to find some time over the next few weeks to figure out the regressions there.

**Comment by stannie** [comment]
Can confirm this for [NEO COOLCAM NAS-DS01Z Z-wave Door Window Sensor](https://www.aliexpress.com/item/32705197236.html) as it is not pairing to the [Z-wave.me USB Stick](https://z-wave.me/products/uzb/) while a power plug did pair properly.

**Comment by matellis** [comment]
Can also confirm this for [Aotec Door/Window Sensor 7](https://www.amazon.com/Aeotec-Window-Contact-sensors-Battery/dp/B07PDDX3K6/) with same error in the logs. It's supported in the Openzwave device database as device designation ZW187. Let me know how I can support testing efforts.
