### ISSUE TITLE
Aeotec Multisensor6

### ISSUE THREAD

**Issue by CVHvisuals** [shnhrrsn/homebridge-openzwave#8]
I am unable to add the Aeotect Multisensor 6. It provides an error posted. I am able to add my other 20 devices no problem, so thank you for that!
Here is the error for the sensor, I am using it with a usb cable for power. macOS Catalina. Zstick Gen5

[6/26/2020, 9:25:15 AM] [OpenZWave] Failed to make accessory Error: homekitToZwave is required for readwrite values
    at new ValueCoordinator (/usr/local/lib/node_modules/homebridge-openzwave/src/Values/ValueCoordinator.ts:44:10)
    at registerCharacteristic (/usr/local/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/Support/registerCharacteristic.ts:27:2)
    at driver (/usr/local/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/batteryDriver.ts:36:2)
    at Accessory.configure (/usr/local/lib/node_modules/homebridge-openzwave/src/Accessories/Accessory.ts:72:4)
    at /usr/local/lib/node_modules/homebridge-openzwave/src/Accessories/AccessoryManager.ts:112:15

**Comment by w21dk** [comment]
Hi @CVHvisuals ,
I'm seeing the same error. The difference is that I haven't been able to add any zwave devices to the hombridge. I press the add node button, and when attempting to add an Aeotec Door/Window Sensor 7 or Recessed Door Sensor 7 I get the following:

_Failed to make accessory Error: homekitToZwave is required for readwrite values
at new ValueCoordinator (/usr/lib/node_modules/homebridge-openzwave/src/Values/ValueCoordinator.ts:51:10)
at registerCharacteristic (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/Support/registerCharacteristic.ts:27:2)
at driver (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Drivers/batteryDriver.ts:36:2)
at Accessory.configure (/usr/lib/node_modules/homebridge-openzwave/src/Accessories/Accessory.ts:72:4)
at /usr/lib/node_modules/homebridge-openzwave/src/Accessories/AccessoryManager.ts:112:15_

**Comment by kenmg77** [comment]
@CVHvisuals @w21dk did you find a solution to your Failed to make accessory Error?

**Comment by w21dk** [comment]
> @CVHvisuals @w21dk did you find a solution to your Failed to make accessory Error?

no, unfortunately I gave up. My z-wave devices are sitting in a box; unused.
I'm hoping an update will fix it.

**Comment by CVHvisuals** [comment]
I ended up switching to Home Assistant and wont look back.
